preset: laravel

enabled:
  - length_ordered_imports
  - concat_with_spaces

disabled:
  - single_class_element_per_statement
  - alpha_ordered_imports
  - concat_without_spaces
  - not_operator_with_successor_space
